version: '3.8'

services:
  usuario:
    image: usuario-app
    build:
      context: ./usuario
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my-network

  carro:
    image: carro-app
    build:
      context: ./carro
      dockerfile: Dockerfile
    ports:
      - "5050:50"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
